VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "base_create_class"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Sub initial(InitialParams As Dictionary)
End Sub

Public Sub showForm()
End Sub

Property Get isFormFill(ByRef curForm As UserForm) As Boolean
End Property

Public Sub create(ByRef cuForm As UserForm)
End Sub
