VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "base_element_class"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

' базовый класс для работы с элементом на форме ListFormNew

Public Sub create()
End Sub

Public Sub delete()
End Sub

Public Sub change()
End Sub

Property Get Name() As String
End Property
