VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "bldn_no_id_class"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

' -----------------------------------------------------------------------------
' 27.09.2022
' класс для списка домов
' -----------------------------------------------------------------------------

Public Id As Long
Public Name As String
Public Address As String
Public reportOut As Boolean
Public mcId As Long
Public siteName As String
Public dogovorType As Long
