VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "village_type"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

' ----------------------------------------------------------------------------
' класс типов населённых пунктов
' ----------------------------------------------------------------------------

Public Id As Long               ' код
Public Name As String           ' название
Public ShortName As String      ' сокращенное название
